# Generated by Django 2.2.3 on 2020-01-06 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urlmapper',
            old_name='timestamp',
            new_name='create',
        ),
    ]
